# Generated by Django 5.2.1 on 2025-06-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0002_datatreinamento_pergunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinamentos',
            old_name='documento',
            new_name='arquivo',
        ),
    ]
